server.port=8080
spring.application.name=4iren-rule-engine

#rabbitMQ
rabbitmq.queue.name=4iren.sensor.processed
rabbitmq.exchange.name=4iren.sensor.exchange
rabbitmq.routing.key=sensor.processed.rule

#jpa

#MySql

#redis

#es,kibana