### 변수 설정
@hostname = localhost
@port = 8085
@baseUrl = http://{{hostname}}:{{port}}/api/rule
@roomId = 1
@nodeId = 1
@tempNodeId = -1



### [노드 설정 유효성 검증] 정상 케이스 테스트
POST {{baseUrl}}/rooms/{{roomId}}/validate-config
Content-Type: application/json

{
  "nodeConfig": {
    "nodeType": "THRESHOLD",
    "x": 200,
    "y": 200,
    "measurementType": "CO2",
    "unit": "ppm",
    "operator": "GTE",
    "threshold": 1200.0
  }
}

### [노드 설정 유효성 검증] 실패 케이스 테스트 (잘못된 필드 누락 등)
POST {{baseUrl}}/rooms/{{roomId}}/validate-config
Content-Type: application/json

{
  "nodeConfig": {
    "nodeType": "AVERAGE",
    "x": 200,
    "y": 200,
    "measurementType": "TEMPERATURE",
    "unit": "°C",
    "operator": "LT",
    "average": 22.0,
    "windowSec": -60
  }
}
